name: hbdirect
favicon: null
layout_spectrum: 0.13397
typography_spectrum: 0.7180121492128819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c4c4c4'
    - '#272528'
    - '#4c638e'
    - '#909cb5'
  brandStrength: 0.15701118600554764
  lightness: 0.018815764226019382
  saturation: 0.8335920919198543
  rhythmicContrast: 0.25
purpose: []
